package kus.hibernate.classes;

// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	private Integer idClass;
	private Teachers teachers;
	private String name;
	private Date startYear;
	private Date endYear;
	private String about;
	private Set<Students> studentses = new HashSet<Students>(0);
	private Set<Schedule> schedules = new HashSet<Schedule>(0);
	private Set<Teachers> teacherses = new HashSet<Teachers>(0);

	public Classes() {
	}

	public Classes(Teachers teachers, String name, Date startYear, Date endYear) {
		this.teachers = teachers;
		this.name = name;
		this.startYear = startYear;
		this.endYear = endYear;
	}

	public Classes(Teachers teachers, String name, Date startYear,
			Date endYear, String about, Set<Students> studentses,
			Set<Schedule> schedules, Set<Teachers> teacherses) {
		this.teachers = teachers;
		this.name = name;
		this.startYear = startYear;
		this.endYear = endYear;
		this.about = about;
		this.studentses = studentses;
		this.schedules = schedules;
		this.teacherses = teacherses;
	}

	public Integer getIdClass() {
		return this.idClass;
	}

	public void setIdClass(Integer idClass) {
		this.idClass = idClass;
	}

	public Teachers getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Teachers teachers) {
		this.teachers = teachers;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartYear() {
		return this.startYear;
	}

	public void setStartYear(Date startYear) {
		this.startYear = startYear;
	}

	public Date getEndYear() {
		return this.endYear;
	}

	public void setEndYear(Date endYear) {
		this.endYear = endYear;
	}

	public String getAbout() {
		return this.about;
	}

	public void setAbout(String about) {
		this.about = about;
	}

	public Set<Students> getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set<Students> studentses) {
		this.studentses = studentses;
	}

	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

	public Set<Teachers> getTeacherses() {
		return this.teacherses;
	}

	public void setTeacherses(Set<Teachers> teacherses) {
		this.teacherses = teacherses;
	}

}
