package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses implements java.io.Serializable {

	private Integer idCourse;
	private String name;
	private String about;
	private Date start;
	private Date end;
	private boolean ongoing;
	private Set<CoursesHasTeachers> coursesHasTeacherses = new HashSet<CoursesHasTeachers>(
			0);
	private Set<Schedule> schedules = new HashSet<Schedule>(0);
	private Set<Marks> markses = new HashSet<Marks>(0);

	public Courses() {
	}

	public Courses(String name, Date start, Date end, boolean ongoing) {
		this.name = name;
		this.start = start;
		this.end = end;
		this.ongoing = ongoing;
	}

	public Courses(String name, String about, Date start, Date end,
			boolean ongoing, Set<CoursesHasTeachers> coursesHasTeacherses,
			Set<Schedule> schedules, Set<Marks> markses) {
		this.name = name;
		this.about = about;
		this.start = start;
		this.end = end;
		this.ongoing = ongoing;
		this.coursesHasTeacherses = coursesHasTeacherses;
		this.schedules = schedules;
		this.markses = markses;
	}

	public Integer getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(Integer idCourse) {
		this.idCourse = idCourse;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAbout() {
		return this.about;
	}

	public void setAbout(String about) {
		this.about = about;
	}

	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public boolean isOngoing() {
		return this.ongoing;
	}

	public void setOngoing(boolean ongoing) {
		this.ongoing = ongoing;
	}

	public Set<CoursesHasTeachers> getCoursesHasTeacherses() {
		return this.coursesHasTeacherses;
	}

	public void setCoursesHasTeacherses(
			Set<CoursesHasTeachers> coursesHasTeacherses) {
		this.coursesHasTeacherses = coursesHasTeacherses;
	}

	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

	public Set<Marks> getMarkses() {
		return this.markses;
	}

	public void setMarkses(Set<Marks> markses) {
		this.markses = markses;
	}

}
