package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

/**
 * CoursesHasTeachers generated by hbm2java
 */
public class CoursesHasTeachers implements java.io.Serializable {

	private Integer coursesHasTeachersId;
	private Teachers teachers;
	private Courses courses;

	public CoursesHasTeachers() {
	}

	public CoursesHasTeachers(Teachers teachers, Courses courses) {
		this.teachers = teachers;
		this.courses = courses;
	}

	public Integer getCoursesHasTeachersId() {
		return this.coursesHasTeachersId;
	}

	public void setCoursesHasTeachersId(Integer coursesHasTeachersId) {
		this.coursesHasTeachersId = coursesHasTeachersId;
	}

	public Teachers getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Teachers teachers) {
		this.teachers = teachers;
	}

	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

}
