package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Lessons generated by hbm2java
 */
public class Lessons implements java.io.Serializable {

	private int idLesson;
	private int idCourse;
	private Date start;
	private Date end;
	private int idteachers;

	public Lessons() {
	}

	public Lessons(int idLesson, int idCourse, Date start, Date end,
			int idteachers) {
		this.idLesson = idLesson;
		this.idCourse = idCourse;
		this.start = start;
		this.end = end;
		this.idteachers = idteachers;
	}

	public int getIdLesson() {
		return this.idLesson;
	}

	public void setIdLesson(int idLesson) {
		this.idLesson = idLesson;
	}

	public int getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(int idCourse) {
		this.idCourse = idCourse;
	}

	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public int getIdteachers() {
		return this.idteachers;
	}

	public void setIdteachers(int idteachers) {
		this.idteachers = idteachers;
	}

}
