package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

/**
 * ParentsHasStudents generated by hbm2java
 */
public class ParentsHasStudents implements java.io.Serializable {

	private Integer parentsHasStudentsId;
	private Students students;
	private Parents parents;

	public ParentsHasStudents() {
	}

	public ParentsHasStudents(Students students, Parents parents) {
		this.students = students;
		this.parents = parents;
	}

	public Integer getParentsHasStudentsId() {
		return this.parentsHasStudentsId;
	}

	public void setParentsHasStudentsId(Integer parentsHasStudentsId) {
		this.parentsHasStudentsId = parentsHasStudentsId;
	}

	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	public Parents getParents() {
		return this.parents;
	}

	public void setParents(Parents parents) {
		this.parents = parents;
	}

}
