package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parents generated by hbm2java
 */
public class Parents implements java.io.Serializable {

	private Integer idParent;
	private Users users;
	private String name;
	private String surname;
	private String phone;
	private String email;
	private String adress;
	private Date dateOfCome;
	private Set<ParentsHasStudents> parentsHasStudentses = new HashSet<ParentsHasStudents>(
			0);

	public Parents() {
	}

	public Parents(Users users, String name, String surname, String adress,
			Date dateOfCome) {
		this.users = users;
		this.name = name;
		this.surname = surname;
		this.adress = adress;
		this.dateOfCome = dateOfCome;
	}

	public Parents(Users users, String name, String surname, String phone,
			String email, String adress, Date dateOfCome,
			Set<ParentsHasStudents> parentsHasStudentses) {
		this.users = users;
		this.name = name;
		this.surname = surname;
		this.phone = phone;
		this.email = email;
		this.adress = adress;
		this.dateOfCome = dateOfCome;
		this.parentsHasStudentses = parentsHasStudentses;
	}

	public Integer getIdParent() {
		return this.idParent;
	}

	public void setIdParent(Integer idParent) {
		this.idParent = idParent;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	public Date getDateOfCome() {
		return this.dateOfCome;
	}

	public void setDateOfCome(Date dateOfCome) {
		this.dateOfCome = dateOfCome;
	}

	public Set<ParentsHasStudents> getParentsHasStudentses() {
		return this.parentsHasStudentses;
	}

	public void setParentsHasStudentses(
			Set<ParentsHasStudents> parentsHasStudentses) {
		this.parentsHasStudentses = parentsHasStudentses;
	}

}
