package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	private Integer idSchedule;
	private Courses courses;
	private Classes classes;
	private Teachers teachers;
	private Date timeStart;
	private Date timeEnd;
	private String day;

	public Schedule() {
	}

	public Schedule(Courses courses, Classes classes, Teachers teachers,
			Date timeStart, Date timeEnd, String day) {
		this.courses = courses;
		this.classes = classes;
		this.teachers = teachers;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.day = day;
	}

	public Integer getIdSchedule() {
		return this.idSchedule;
	}

	public void setIdSchedule(Integer idSchedule) {
		this.idSchedule = idSchedule;
	}

	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public Teachers getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Teachers teachers) {
		this.teachers = teachers;
	}

	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

}
