package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

	private Integer idStudent;
	private Users users;
	private Classes classes;
	private String name;
	private String surname;
	private String phone;
	private String email;
	private String adress;
	private Date dateOfCome;
	private Set<Listofpresent> listofpresents = new HashSet<Listofpresent>(0);
	private Set<ParentsHasStudents> parentsHasStudentses = new HashSet<ParentsHasStudents>(
			0);
	private Set<Marks> markses = new HashSet<Marks>(0);

	public Students() {
	}

	public Students(Users users, String name, String surname, String adress,
			Date dateOfCome) {
		this.users = users;
		this.name = name;
		this.surname = surname;
		this.adress = adress;
		this.dateOfCome = dateOfCome;
	}

	public Students(Users users, Classes classes, String name, String surname,
			String phone, String email, String adress, Date dateOfCome,
			Set<Listofpresent> listofpresents,
			Set<ParentsHasStudents> parentsHasStudentses, Set<Marks> markses) {
		this.users = users;
		this.classes = classes;
		this.name = name;
		this.surname = surname;
		this.phone = phone;
		this.email = email;
		this.adress = adress;
		this.dateOfCome = dateOfCome;
		this.listofpresents = listofpresents;
		this.parentsHasStudentses = parentsHasStudentses;
		this.markses = markses;
	}

	public Integer getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(Integer idStudent) {
		this.idStudent = idStudent;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	public Date getDateOfCome() {
		return this.dateOfCome;
	}

	public void setDateOfCome(Date dateOfCome) {
		this.dateOfCome = dateOfCome;
	}

	public Set<Listofpresent> getListofpresents() {
		return this.listofpresents;
	}

	public void setListofpresents(Set<Listofpresent> listofpresents) {
		this.listofpresents = listofpresents;
	}

	public Set<ParentsHasStudents> getParentsHasStudentses() {
		return this.parentsHasStudentses;
	}

	public void setParentsHasStudentses(
			Set<ParentsHasStudents> parentsHasStudentses) {
		this.parentsHasStudentses = parentsHasStudentses;
	}

	public Set<Marks> getMarkses() {
		return this.markses;
	}

	public void setMarkses(Set<Marks> markses) {
		this.markses = markses;
	}

}
