package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.Range;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userId;
	@NotNull
	private String login;
	@NotNull
	@Size(min=6,max=15)
	private String password;
	private byte enabled;
	private Set<Students> studentses = new HashSet<Students>(0);
	private Set<Userroles> userroleses = new HashSet<Userroles>(0);
	private Set<Parents> parentses = new HashSet<Parents>(0);
	private Set<Teachers> teacherses = new HashSet<Teachers>(0);

	public Users() {
	}

	public Users(String login, String password, byte enabled) {
		this.login = login;
		this.password = password;
		this.enabled = enabled;
	}

	public Users(String login, String password, byte enabled,
			Set<Students> studentses, Set<Userroles> userroleses,
			Set<Parents> parentses, Set<Teachers> teacherses) {
		this.login = login;
		this.password = password;
		this.enabled = enabled;
		this.studentses = studentses;
		this.userroleses = userroleses;
		this.parentses = parentses;
		this.teacherses = teacherses;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	public Set<Students> getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set<Students> studentses) {
		this.studentses = studentses;
	}

	public Set<Userroles> getUserroleses() {
		return this.userroleses;
	}

	public void setUserroleses(Set<Userroles> userroleses) {
		this.userroleses = userroleses;
	}

	public Set<Parents> getParentses() {
		return this.parentses;
	}

	public void setParentses(Set<Parents> parentses) {
		this.parentses = parentses;
	}

	public Set<Teachers> getTeacherses() {
		return this.teacherses;
	}

	public void setTeacherses(Set<Teachers> teacherses) {
		this.teacherses = teacherses;
	}

}
