package kus.hibernate.classes;


// default package
// Generated 2013-11-16 20:27:54 by Hibernate Tools 4.0.0

/**
 * Userroles generated by hbm2java
 */
public class Userroles implements java.io.Serializable {

	private Integer userRolesId;
	private Users users;
	private String authority;

	public Userroles() {
	}

	public Userroles(Users users, String authority) {
		this.users = users;
		this.authority = authority;
	}

	public Integer getUserRolesId() {
		return this.userRolesId;
	}

	public void setUserRolesId(Integer userRolesId) {
		this.userRolesId = userRolesId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
